### ISSUE TITLE
New fields in Wishes

### ISSUE THREAD

**Issue by null09264** [Wishes-CS3216/Wishes-Backend#17]
In order for the timeline in wish detail view to function, some extra fields are needed in the wishes:

```

assignee_contact: "88888888",
assignee_display_name: "Jay Chow",
picked_at:"2016-09-20T11:11:26.000Z",
fulfilled_at:"2016-09-21T11:11:26.000Z",
confirmed_at:"2016-09-21T14:11:26.000Z"

```

Front-end will judge the status of the wish based on the existence of these fields

**Comment by Melvin-Tan** [comment]
Which part of the API is this needed? The index action for GET /api/v1/users/:user_id/wishes right? o.o

**Comment by null09264** [comment]
All parts related to wish, these fields should be new columns in the Wish table

**Comment by null09264** [comment]
![screen shot 2016-09-21 at 8 14 48 pm](https://cloud.githubusercontent.com/assets/4215068/18710482/15ebd204-8038-11e6-93cf-fa9d007eb83b.png)

**Comment by Melvin-Tan** [comment]
created_at, picked_at, fulfilled_at and confirmed_at

If you judge by this metric it might be unclear for corner cases leh?
Suppose I am do-er you are wish-er
Like if say I mark as fulfilled u mark as unfulfilled, how should confirmed_at be done?
There could be other cases that I haven't try to think of.

Furthermore having an enum for status might be more verbose for frontend as well, right? o.o 

Ok actually the main reason is simply because I have already implemented the logic and is lazy to undo. But i think the concerns are real :P
